slam_toolbox:
  ros__parameters:
    resolution: 0.05
    max_laser_range: 25.0
    message_filter_queue_size: 25
    update_min_d: 0.25
    update_min_a: 0.2
    laser_z_min_value: -1.0
    laser_z_max_value: 1.0